build-docker:
  stage: build
  extends: .aws-auth
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    IMAGE_TAG: "${CI_COMMIT_SHORT_SHA}"
  script:
    - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
    - docker build -t ${ECR_REGISTRY}/notes-app:${IMAGE_TAG} ./app
    - docker push ${ECR_REGISTRY}/notes-app:${IMAGE_TAG}
  only:
    - main